version: '3.8'

services:
  web-app:
    image: suitecrm
    container_name: suitecrm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    container_name: mysql-suitecrm
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=suitecrm-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=suitecrm-db
    ports:
      - "13306:3306"




